---
title: "figures"
author: "Anne Baranger"
date: "2024-07-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
lapply(c("targets","stringr","tidyr","dplyr","tibble", # data analysis
         "ggplot2","viridis","ggridges", # plot
         "rstan","shinystan","BIOMASS",# stat & models
         "rworldmap" # geographic data #terre, sf
         ),require,character.only=TRUE)
```

# Trajectories with systori model

## With global fits concatenation
```{r}
traj<-tar_read(global_fit_systori)$trajectory
fit<-tar_read(global_fit_systori)$fit_df
tar_load(mod.data)
tar_load(correspondance_table)
trajectories<-ggplot(data=traj)+
  geom_point(data=mod.data,aes(dbh,H,color=system),alpha=0.1)+
  geom_ribbon(aes(dbh,ymin=H_q05,ymax=H_q95,group=system),fill="grey",alpha=0.5)+
  geom_line(aes(dbh,H_med,group=system,color=system))+
  facet_wrap(~origin)+
  scale_color_manual(labels=c("Forest","Secondary forest","Plantation","Agroforestry"),
                     values=c("forestgreen","lightgreen","steelblue3","lightsalmon"))+
  scale_y_log10()+
  theme(legend.position = "top")+
  labs(color="System")
alpha<-fit |> 
  select(matches("alpha")&!matches("_0")) |> 
  pivot_longer(cols=everything()) |> 
  mutate(name=str_replace(name,"alpha_",""))|>
  left_join(correspondance_table,by=c("name"="corr")) |> 
  mutate(system=ordered(system,
                        levels=c("forest","secondary_forest","plantation","agroforestry"))) |> 
  ggplot(aes(value,system,fill=system))+
  geom_density_ridges(scale=0.8)+
  scale_fill_manual(labels=c("Forest","Secondary forest","Plantation","Agroforestry"),
                     values=c("forestgreen","lightgreen","steelblue3","lightsalmon"))+
  facet_wrap(~origin)+
  theme(axis.text.y = element_text(color="white",angle=90),
        axis.ticks.y = element_line(color="white"))+
  theme(legend.position = "none")+
  labs(y="",x="Alpha value")
beta<-fit |> 
  select(matches("beta")&!matches("_0")) |> 
  pivot_longer(cols=everything()) |> 
  mutate(name=str_replace(name,"beta_","")) |> 
  left_join(correspondance_table,by=c("name"="corr")) |> 
  mutate(system=ordered(system,
                        levels=c("forest","secondary_forest","plantation","agroforestry"))) |>
  ggplot(aes(value,system,fill=system))+
  geom_density_ridges(scale=0.8)+
  scale_fill_manual(labels=c("Forest","Secondary forest","Plantation","Agroforestry"),
                     values=c("forestgreen","lightgreen","steelblue3","lightsalmon"))+
  facet_wrap(~origin)+
  theme(axis.text.y = element_text(color="white",angle=90),
        axis.ticks.y = element_line(color="white"))+
  theme(legend.position = "none")+
  labs(y="",x="Beta value")
cowplot::plot_grid(trajectories,alpha,beta,nrow=3,rel_heights = c(1,0.6,0.6))
```
## With fit from subdataset

```{r}
traj_sub<-tar_read(subdata_fit_systori)$trajectory
fit_sub<-tar_read(subdata_fit_systori)$fit_df
tar_load(mod.data)
tar_load(correspondance_table)
trajectories<-ggplot(data=traj_sub)+
  geom_point(data=mod.data,aes(dbh,H,color=system),alpha=0.1)+
  geom_ribbon(aes(dbh,ymin=H_q05,ymax=H_q95,group=system),fill="grey",alpha=0.5)+
  geom_line(aes(dbh,H_med,group=system,color=system))+
  facet_wrap(~origin)+
  scale_color_manual(labels=c("Forest","Secondary forest","Plantation","Agroforestry"),
                     values=c("forestgreen","lightgreen","steelblue3","lightsalmon"))+
  scale_y_log10()+
  theme(legend.position = "top")+
  labs(color="System")
alpha<-fit_sub |> 
  select(matches("alpha")&!matches("_0")) |> 
  pivot_longer(cols=everything()) |> 
  mutate(name=str_replace(name,"alpha_",""))|>
  left_join(correspondance_table,by=c("name"="corr")) |> 
  mutate(system=ordered(system,
                        levels=c("forest","secondary_forest","plantation","agroforestry"))) |> 
  ggplot(aes(value,system,fill=system))+
  geom_density_ridges(scale=0.8)+
  scale_fill_manual(labels=c("Forest","Secondary forest","Plantation","Agroforestry"),
                     values=c("forestgreen","lightgreen","steelblue3","lightsalmon"))+
  facet_wrap(~origin)+
  theme(axis.text.y = element_text(color="white",angle=90),
        axis.ticks.y = element_line(color="white"))+
  theme(legend.position = "none")+
  labs(y="",x="Alpha value")
beta<-fit_sub |> 
  select(matches("beta")&!matches("_0")) |> 
  pivot_longer(cols=everything()) |> 
  mutate(name=str_replace(name,"beta_","")) |> 
  left_join(correspondance_table,by=c("name"="corr")) |> 
  mutate(system=ordered(system,
                        levels=c("forest","secondary_forest","plantation","agroforestry"))) |>
  ggplot(aes(value,system,fill=system))+
  geom_density_ridges(scale=0.8)+
  scale_fill_manual(labels=c("Forest","Secondary forest","Plantation","Agroforestry"),
                     values=c("forestgreen","lightgreen","steelblue3","lightsalmon"))+
  facet_wrap(~origin)+
  theme(axis.text.y = element_text(color="white",angle=90),
        axis.ticks.y = element_line(color="white"))+
  theme(legend.position = "none")+
  labs(y="",x="Beta value")
cowplot::plot_grid(trajectories,alpha,beta,nrow=3,rel_heights = c(1,0.6,0.6))
```

# Biomass predictions

```{r}
predict_fit_systori<-tar_read(subdata_fit_systori)$data_pred |>
  select(!c(cof,num,corr)) |> mutate(mod="systori_sub",cluster=as.factor(0))
dataWD <- getWoodDensity(
  genus = predict_fit_systori$genusCorr,
  species = predict_fit_systori$speciesCorr,
  stand = predict_fit_systori$id_plot)
predict_fit_systori$AGBobs<- computeAGB(D = predict_fit_systori$dbh,
                                             WD = dataWD$meanWD,
                                             H = predict_fit_systori$H)
predict_fit_systori$AGBpred<- computeAGB(D = predict_fit_systori$dbh,
                                              WD = dataWD$meanWD,
                                              H = predict_fit_systori$H_med)
# Hpred_chave <- computeAGB(D = predict_fit_systori$dbh,
                                              # WD = dataWD$meanWD,
                                              # H = predict_fit_systori$H_med)

tar_load(predict_spatial_crossval)
dataWD <- getWoodDensity(
  genus = predict_spatial_crossval$genusCorr,
  species = predict_spatial_crossval$speciesCorr,
  stand = predict_spatial_crossval$id_plot)
predict_spatial_crossval$AGBobs<- computeAGB(D = predict_spatial_crossval$dbh,
                                             WD = dataWD$meanWD,
                                             H = predict_spatial_crossval$H)
predict_spatial_crossval$AGBpred<- computeAGB(D = predict_spatial_crossval$dbh,
                                              WD = dataWD$meanWD,
                                              H = predict_spatial_crossval$H_med)
Hpred_chave <- computeAGB(D = predict_spatial_crossval$dbh,
                                              WD = dataWD$meanWD,
                                              H = predict_spatial_crossval$H_med)
# rbind(predict_spatial_crossval,
#       predict_fit_systori) |> 
predict_spatial_crossval |> 
  mutate(dh=(H_med-H)/H,
         sep_h=H-H_med,
         dAGB=100*(AGBpred-H_med)/AGBobs,
         mod=factor(mod,levels=c("nul_mod","origin","system","systori_sub","systori","complete"))) |> 
  filter(mod!="complete") |> 
  group_by(system,id_plot,mod) |> 
  summarise(AGBpred_plot=sum(AGBpred),
            AGBobs_plot=sum(AGBobs),
            dAGB_plot=100*(AGBpred_plot-AGBobs_plot)/AGBobs_plot) |> 
  ggplot(aes(as.factor(mod),dAGB_plot,fill=as.factor(mod)))+
  geom_boxplot()+
  geom_hline(yintercept=0)+
  theme_light()+
  theme(legend.position="none")+
  facet_wrap(~system)+
  labs(x="Model",
       y="Error in predicted biomass per plot (%)")

predict_spatial_crossval |> 
mutate(dh=100*(H_med-H)/H,
         sep_h=H-H_med,
         dAGB=100*(AGBpred-AGBobs)/AGBobs,
         mod=factor(mod,levels=c("nul_mod","origin","system","systori_sub","systori","complete"))) |> 
  filter(mod!="complete") |> 
  ggplot(aes(as.factor(mod),dAGB,fill=as.factor(mod)))+
  geom_boxplot()+
  geom_hline(yintercept=0)+
  theme_light()+
  theme(legend.position="none")+
  facet_wrap(~system)+
  labs(x="Model",
       y="Error in predicted biomass (%)")+
    ylim(c(-100,200))

  
  # filter(H>1) |> 
  # filter(!(H<2&dbh>7.5)) |>
  # filter(dh>(-10)) |> 
  ggplot(aes(as.factor(mod),sep_h,fill=as.factor(mod)))+
  geom_boxplot()+
  geom_hline(yintercept=0)+
  theme_light()+
  facet_wrap(~origin)
  ylim(c(-20,20))
  
  load("mod_spatial_cross_valid/subdata_3_nul_mod.RData")
  
  load("mod_spatial_cross_valid/subdata_14_system.RData")
```

# block map
```{r}
civ_map=sf::read_sf(dsn="data/civ/",
                layer="COTE D'IVE")

predict_spatial_crossval |> 
  select(systori,system,id_plot,lat,long,cluster) |>
  distinct() |> 
  ggplot(aes(lat,long,color=cluster))+
  geom_point() +
  facet_wrap(~system)
  
```

